// GENERATED by tools/gen_world_map.py - DO NOT EDIT BY HAND.
//
// World land outline for ui/spot_map_view.c.
//
// Originally contributed by Uwe DL8UG, ported from his rbn_monitor project as
// a 1:110m silhouette in tenths of a degree. Regenerated 2026-09-12 at higher
// resolution because the map zooms and the silhouette did not survive it (the
// operator: "far too coarse when zoomed in to Scandinavia").
//
// Source: Natural Earth 1:50m land polygons (public domain), via
// https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_10m_land.geojson
// Douglas-Peucker tolerance 0.05 deg; rings with a bounding box smaller
// than 0.15 deg are dropped. 1744 rings, 38587 points.
#pragma once

#include <stdint.h>

// ⛔ COORDINATES ARE HUNDREDTHS OF A DEGREE - divide by 100.0, not 10.0.
//
// The previous generation of this table used TENTHS. Hundredths cost nothing
// (longitude reaches +-18000 and latitude +-9000, both inside int16_t) and
// remove the visible stair-stepping when zoomed: at 12x one step is ~0.35 px
// instead of ~3.5 px.
#define WORLD_MAP_UNITS_PER_DEG 100.0f

// Each ring is an implicitly closed polygon outline - the renderer draws the
// edge from the last point back to the first, so do not repeat point 0.
//
// ⭐ THE BOUNDING BOX IS LOAD-BEARING, NOT METADATA. LVGL 9.2.2's
// lv_draw_line_dsc_t is a single segment, so the renderer issues one draw call
// per EDGE. This table is ~16x denser than the silhouette it replaced, and the
// spot map's redraw cost is already implicated in audio-ring overflows on this
// board. Reject a ring by its box (two projections) before walking its points,
// and skip one that projects smaller than a pixel or two - that makes the
// zoomed-in case cheaper than the old coarse table was, and lets the small
// islands cost nothing at low zoom.
typedef struct {
    const int16_t *points;    // interleaved lon,lat pairs, hundredths of a degree
    uint16_t point_count;
    int16_t  lon_min, lat_min, lon_max, lat_max;   // hundredths of a degree
} world_map_ring_t;

extern const world_map_ring_t WORLD_MAP_RINGS[];
extern const int WORLD_MAP_RING_COUNT;
